version: "3"
services:
  picture_api:

    image: docker.io/root0877/picture_api:6bbe063b21b79923f5d257e7ea8b278656f1cb09
    ports:
      - 9000:9000
    container_name: picture-api
    restart: always

  image_miner:
    image: docker.io/root0877/image_miner:fa81c23c6936314fd87bfe077f03a44a57acea18
    ports:
      - 8000:8000
    container_name: image-miner
    restart: always

  frontend:
    image: docker.io/root0877/miner_frontend:${IMAGE_TAG}
    ports:
      - 3000:3000
    container_name: frontend
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - picture_api
      - image_miner
    